
usb-modeswitch-1.2.4_URL         = \
	http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-1.2.4.tar.bz2

usb-modeswitch-data-20120815_URL = \
	http://www.draisberghof.de/usb_modeswitch/usb-modeswitch-data-20120815.tar.bz2

MAKEVARS     = CC="$(CC) $(CFLAGS)" LIBS="-lusb -lpthread"
AUTOMAKE_y   += usb-modeswitch-1.2.4 usb-modeswitch-data-20120815

include $(ROOTDIR)/tools/automake.inc

