
URL      = git://nbd.name/uci.git
METHOD   = git
AUTOCONF = cmake CMakeLists.txt
AUTOCONF += -DBUILD_LUA=0
AUTOCONF += -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_SYSTEM_PREFIX_PATH=$(STAGEDIR)

include $(ROOTDIR)/tools/automake.inc

